<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{26a15cae-5634-4149-81e6-7ccf156c7169}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	FuelMeasurement : FuelMeasurement;
	recordedTime : TIME ;
	valveClose : BOOL ;
	FuelVolumePerSec : REAL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[FuelMeasurement(CloseValve => GVL.valveClose, timeElapsed => recordedTime, FuelVolumePerSec => FuelVolumePerSec);

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="57" Count="0" />
      <LineId Id="44" Count="0" />
      <LineId Id="43" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>